// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofile/ChatModule.proto

package com.cn.common.module.chat.proto;

public final class ChatModule {
  private ChatModule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ChatType
      implements com.google.protobuf.ProtocolMessageEnum {
    PRIVATE(0, 0),
    PUBLIC(1, 1),
    ;
    
    public static final int PRIVATE_VALUE = 0;
    public static final int PUBLIC_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static ChatType valueOf(int value) {
      switch (value) {
        case 0: return PRIVATE;
        case 1: return PUBLIC;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ChatType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ChatType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChatType>() {
            public ChatType findValueByNumber(int number) {
              return ChatType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cn.common.module.chat.proto.ChatModule.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ChatType[] VALUES = {
      PRIVATE, PUBLIC, 
    };
    
    public static ChatType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ChatType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:ChatType)
  }
  
  public interface PrivateChatRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 targetPlayerId = 1;
    boolean hasTargetPlayerId();
    long getTargetPlayerId();
    
    // required string context = 2;
    boolean hasContext();
    String getContext();
  }
  public static final class PrivateChatRequest extends
      com.google.protobuf.GeneratedMessage
      implements PrivateChatRequestOrBuilder {
    // Use PrivateChatRequest.newBuilder() to construct.
    private PrivateChatRequest(Builder builder) {
      super(builder);
    }
    private PrivateChatRequest(boolean noInit) {}
    
    private static final PrivateChatRequest defaultInstance;
    public static PrivateChatRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public PrivateChatRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.module.chat.proto.ChatModule.internal_static_PrivateChatRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.module.chat.proto.ChatModule.internal_static_PrivateChatRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 targetPlayerId = 1;
    public static final int TARGETPLAYERID_FIELD_NUMBER = 1;
    private long targetPlayerId_;
    public boolean hasTargetPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTargetPlayerId() {
      return targetPlayerId_;
    }
    
    // required string context = 2;
    public static final int CONTEXT_FIELD_NUMBER = 2;
    private java.lang.Object context_;
    public boolean hasContext() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          context_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      targetPlayerId_ = 0L;
      context_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTargetPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, targetPlayerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContextBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, targetPlayerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.module.chat.proto.ChatModule.PrivateChatRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.module.chat.proto.ChatModule.internal_static_PrivateChatRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.module.chat.proto.ChatModule.internal_static_PrivateChatRequest_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        targetPlayerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest.getDescriptor();
      }
      
      public com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest getDefaultInstanceForType() {
        return com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest.getDefaultInstance();
      }
      
      public com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest build() {
        com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest buildPartial() {
        com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest result = new com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.targetPlayerId_ = targetPlayerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.context_ = context_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest) {
          return mergeFrom((com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest other) {
        if (other == com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest.getDefaultInstance()) return this;
        if (other.hasTargetPlayerId()) {
          setTargetPlayerId(other.getTargetPlayerId());
        }
        if (other.hasContext()) {
          setContext(other.getContext());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTargetPlayerId()) {
          
          return false;
        }
        if (!hasContext()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              targetPlayerId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              context_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 targetPlayerId = 1;
      private long targetPlayerId_ ;
      public boolean hasTargetPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTargetPlayerId() {
        return targetPlayerId_;
      }
      public Builder setTargetPlayerId(long value) {
        bitField0_ |= 0x00000001;
        targetPlayerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTargetPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetPlayerId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string context = 2;
      private java.lang.Object context_ = "";
      public boolean hasContext() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          context_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContext(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        context_ = value;
        onChanged();
        return this;
      }
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000002);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      void setContext(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        context_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:PrivateChatRequest)
    }
    
    static {
      defaultInstance = new PrivateChatRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PrivateChatRequest)
  }
  
  public interface PublicChatRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string context = 1;
    boolean hasContext();
    String getContext();
  }
  public static final class PublicChatRequest extends
      com.google.protobuf.GeneratedMessage
      implements PublicChatRequestOrBuilder {
    // Use PublicChatRequest.newBuilder() to construct.
    private PublicChatRequest(Builder builder) {
      super(builder);
    }
    private PublicChatRequest(boolean noInit) {}
    
    private static final PublicChatRequest defaultInstance;
    public static PublicChatRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public PublicChatRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.module.chat.proto.ChatModule.internal_static_PublicChatRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.module.chat.proto.ChatModule.internal_static_PublicChatRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string context = 1;
    public static final int CONTEXT_FIELD_NUMBER = 1;
    private java.lang.Object context_;
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          context_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      context_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContextBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.module.chat.proto.ChatModule.PublicChatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PublicChatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PublicChatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PublicChatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PublicChatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PublicChatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PublicChatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.chat.proto.ChatModule.PublicChatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.chat.proto.ChatModule.PublicChatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.PublicChatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.module.chat.proto.ChatModule.PublicChatRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.module.chat.proto.ChatModule.PublicChatRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.module.chat.proto.ChatModule.internal_static_PublicChatRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.module.chat.proto.ChatModule.internal_static_PublicChatRequest_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.module.chat.proto.ChatModule.PublicChatRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.module.chat.proto.ChatModule.PublicChatRequest.getDescriptor();
      }
      
      public com.cn.common.module.chat.proto.ChatModule.PublicChatRequest getDefaultInstanceForType() {
        return com.cn.common.module.chat.proto.ChatModule.PublicChatRequest.getDefaultInstance();
      }
      
      public com.cn.common.module.chat.proto.ChatModule.PublicChatRequest build() {
        com.cn.common.module.chat.proto.ChatModule.PublicChatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.module.chat.proto.ChatModule.PublicChatRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.module.chat.proto.ChatModule.PublicChatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.module.chat.proto.ChatModule.PublicChatRequest buildPartial() {
        com.cn.common.module.chat.proto.ChatModule.PublicChatRequest result = new com.cn.common.module.chat.proto.ChatModule.PublicChatRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.context_ = context_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.module.chat.proto.ChatModule.PublicChatRequest) {
          return mergeFrom((com.cn.common.module.chat.proto.ChatModule.PublicChatRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.module.chat.proto.ChatModule.PublicChatRequest other) {
        if (other == com.cn.common.module.chat.proto.ChatModule.PublicChatRequest.getDefaultInstance()) return this;
        if (other.hasContext()) {
          setContext(other.getContext());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasContext()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              context_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string context = 1;
      private java.lang.Object context_ = "";
      public boolean hasContext() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          context_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContext(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000001);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      void setContext(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:PublicChatRequest)
    }
    
    static {
      defaultInstance = new PublicChatRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PublicChatRequest)
  }
  
  public interface ChatResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 sendPlayerId = 1;
    boolean hasSendPlayerId();
    long getSendPlayerId();
    
    // required string sendPlayerName = 2;
    boolean hasSendPlayerName();
    String getSendPlayerName();
    
    // optional string targetPlayerName = 3 [default = ""];
    boolean hasTargetPlayerName();
    String getTargetPlayerName();
    
    // required .ChatType chatType = 4 [default = PUBLIC];
    boolean hasChatType();
    com.cn.common.module.chat.proto.ChatModule.ChatType getChatType();
    
    // required string message = 5;
    boolean hasMessage();
    String getMessage();
  }
  public static final class ChatResponse extends
      com.google.protobuf.GeneratedMessage
      implements ChatResponseOrBuilder {
    // Use ChatResponse.newBuilder() to construct.
    private ChatResponse(Builder builder) {
      super(builder);
    }
    private ChatResponse(boolean noInit) {}
    
    private static final ChatResponse defaultInstance;
    public static ChatResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.module.chat.proto.ChatModule.internal_static_ChatResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.module.chat.proto.ChatModule.internal_static_ChatResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 sendPlayerId = 1;
    public static final int SENDPLAYERID_FIELD_NUMBER = 1;
    private long sendPlayerId_;
    public boolean hasSendPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getSendPlayerId() {
      return sendPlayerId_;
    }
    
    // required string sendPlayerName = 2;
    public static final int SENDPLAYERNAME_FIELD_NUMBER = 2;
    private java.lang.Object sendPlayerName_;
    public boolean hasSendPlayerName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSendPlayerName() {
      java.lang.Object ref = sendPlayerName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sendPlayerName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSendPlayerNameBytes() {
      java.lang.Object ref = sendPlayerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sendPlayerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string targetPlayerName = 3 [default = ""];
    public static final int TARGETPLAYERNAME_FIELD_NUMBER = 3;
    private java.lang.Object targetPlayerName_;
    public boolean hasTargetPlayerName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTargetPlayerName() {
      java.lang.Object ref = targetPlayerName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          targetPlayerName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTargetPlayerNameBytes() {
      java.lang.Object ref = targetPlayerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        targetPlayerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .ChatType chatType = 4 [default = PUBLIC];
    public static final int CHATTYPE_FIELD_NUMBER = 4;
    private com.cn.common.module.chat.proto.ChatModule.ChatType chatType_;
    public boolean hasChatType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.cn.common.module.chat.proto.ChatModule.ChatType getChatType() {
      return chatType_;
    }
    
    // required string message = 5;
    public static final int MESSAGE_FIELD_NUMBER = 5;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sendPlayerId_ = 0L;
      sendPlayerName_ = "";
      targetPlayerName_ = "";
      chatType_ = com.cn.common.module.chat.proto.ChatModule.ChatType.PUBLIC;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSendPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSendPlayerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChatType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sendPlayerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSendPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTargetPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, chatType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sendPlayerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSendPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTargetPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, chatType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.module.chat.proto.ChatModule.ChatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.ChatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.ChatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.ChatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.ChatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.ChatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.ChatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.chat.proto.ChatModule.ChatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.chat.proto.ChatModule.ChatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.chat.proto.ChatModule.ChatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.module.chat.proto.ChatModule.ChatResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.module.chat.proto.ChatModule.ChatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.module.chat.proto.ChatModule.internal_static_ChatResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.module.chat.proto.ChatModule.internal_static_ChatResponse_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.module.chat.proto.ChatModule.ChatResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sendPlayerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        sendPlayerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        targetPlayerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        chatType_ = com.cn.common.module.chat.proto.ChatModule.ChatType.PUBLIC;
        bitField0_ = (bitField0_ & ~0x00000008);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.module.chat.proto.ChatModule.ChatResponse.getDescriptor();
      }
      
      public com.cn.common.module.chat.proto.ChatModule.ChatResponse getDefaultInstanceForType() {
        return com.cn.common.module.chat.proto.ChatModule.ChatResponse.getDefaultInstance();
      }
      
      public com.cn.common.module.chat.proto.ChatModule.ChatResponse build() {
        com.cn.common.module.chat.proto.ChatModule.ChatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.module.chat.proto.ChatModule.ChatResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.module.chat.proto.ChatModule.ChatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.module.chat.proto.ChatModule.ChatResponse buildPartial() {
        com.cn.common.module.chat.proto.ChatModule.ChatResponse result = new com.cn.common.module.chat.proto.ChatModule.ChatResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sendPlayerId_ = sendPlayerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sendPlayerName_ = sendPlayerName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.targetPlayerName_ = targetPlayerName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.chatType_ = chatType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.module.chat.proto.ChatModule.ChatResponse) {
          return mergeFrom((com.cn.common.module.chat.proto.ChatModule.ChatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.module.chat.proto.ChatModule.ChatResponse other) {
        if (other == com.cn.common.module.chat.proto.ChatModule.ChatResponse.getDefaultInstance()) return this;
        if (other.hasSendPlayerId()) {
          setSendPlayerId(other.getSendPlayerId());
        }
        if (other.hasSendPlayerName()) {
          setSendPlayerName(other.getSendPlayerName());
        }
        if (other.hasTargetPlayerName()) {
          setTargetPlayerName(other.getTargetPlayerName());
        }
        if (other.hasChatType()) {
          setChatType(other.getChatType());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSendPlayerId()) {
          
          return false;
        }
        if (!hasSendPlayerName()) {
          
          return false;
        }
        if (!hasChatType()) {
          
          return false;
        }
        if (!hasMessage()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sendPlayerId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sendPlayerName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              targetPlayerName_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.cn.common.module.chat.proto.ChatModule.ChatType value = com.cn.common.module.chat.proto.ChatModule.ChatType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                chatType_ = value;
              }
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              message_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 sendPlayerId = 1;
      private long sendPlayerId_ ;
      public boolean hasSendPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getSendPlayerId() {
        return sendPlayerId_;
      }
      public Builder setSendPlayerId(long value) {
        bitField0_ |= 0x00000001;
        sendPlayerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSendPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sendPlayerId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string sendPlayerName = 2;
      private java.lang.Object sendPlayerName_ = "";
      public boolean hasSendPlayerName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getSendPlayerName() {
        java.lang.Object ref = sendPlayerName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sendPlayerName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSendPlayerName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sendPlayerName_ = value;
        onChanged();
        return this;
      }
      public Builder clearSendPlayerName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sendPlayerName_ = getDefaultInstance().getSendPlayerName();
        onChanged();
        return this;
      }
      void setSendPlayerName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        sendPlayerName_ = value;
        onChanged();
      }
      
      // optional string targetPlayerName = 3 [default = ""];
      private java.lang.Object targetPlayerName_ = "";
      public boolean hasTargetPlayerName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getTargetPlayerName() {
        java.lang.Object ref = targetPlayerName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          targetPlayerName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTargetPlayerName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        targetPlayerName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTargetPlayerName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        targetPlayerName_ = getDefaultInstance().getTargetPlayerName();
        onChanged();
        return this;
      }
      void setTargetPlayerName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        targetPlayerName_ = value;
        onChanged();
      }
      
      // required .ChatType chatType = 4 [default = PUBLIC];
      private com.cn.common.module.chat.proto.ChatModule.ChatType chatType_ = com.cn.common.module.chat.proto.ChatModule.ChatType.PUBLIC;
      public boolean hasChatType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.cn.common.module.chat.proto.ChatModule.ChatType getChatType() {
        return chatType_;
      }
      public Builder setChatType(com.cn.common.module.chat.proto.ChatModule.ChatType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        chatType_ = value;
        onChanged();
        return this;
      }
      public Builder clearChatType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chatType_ = com.cn.common.module.chat.proto.ChatModule.ChatType.PUBLIC;
        onChanged();
        return this;
      }
      
      // required string message = 5;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        message_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:ChatResponse)
    }
    
    static {
      defaultInstance = new ChatResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ChatResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PrivateChatRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PrivateChatRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicChatRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PublicChatRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChatResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032protofile/ChatModule.proto\"=\n\022PrivateC" +
      "hatRequest\022\026\n\016targetPlayerId\030\001 \002(\003\022\017\n\007co" +
      "ntext\030\002 \002(\t\"$\n\021PublicChatRequest\022\017\n\007cont" +
      "ext\030\001 \002(\t\"\216\001\n\014ChatResponse\022\024\n\014sendPlayer" +
      "Id\030\001 \002(\003\022\026\n\016sendPlayerName\030\002 \002(\t\022\032\n\020targ" +
      "etPlayerName\030\003 \001(\t:\000\022#\n\010chatType\030\004 \002(\0162\t" +
      ".ChatType:\006PUBLIC\022\017\n\007message\030\005 \002(\t*#\n\010Ch" +
      "atType\022\013\n\007PRIVATE\020\000\022\n\n\006PUBLIC\020\001B-\n\037com.c" +
      "n.common.module.chat.protoB\nChatModule"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PrivateChatRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PrivateChatRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PrivateChatRequest_descriptor,
              new java.lang.String[] { "TargetPlayerId", "Context", },
              com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest.class,
              com.cn.common.module.chat.proto.ChatModule.PrivateChatRequest.Builder.class);
          internal_static_PublicChatRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PublicChatRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PublicChatRequest_descriptor,
              new java.lang.String[] { "Context", },
              com.cn.common.module.chat.proto.ChatModule.PublicChatRequest.class,
              com.cn.common.module.chat.proto.ChatModule.PublicChatRequest.Builder.class);
          internal_static_ChatResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ChatResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ChatResponse_descriptor,
              new java.lang.String[] { "SendPlayerId", "SendPlayerName", "TargetPlayerName", "ChatType", "Message", },
              com.cn.common.module.chat.proto.ChatModule.ChatResponse.class,
              com.cn.common.module.chat.proto.ChatModule.ChatResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
