// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofile/PlayerModule.proto

package com.cn.common.module.player.proto;

public final class PlayerModule {
  private PlayerModule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string playerName = 1;
    boolean hasPlayerName();
    String getPlayerName();
    
    // required string passward = 2;
    boolean hasPassward();
    String getPassward();
  }
  public static final class LoginRequest extends
      com.google.protobuf.GeneratedMessage
      implements LoginRequestOrBuilder {
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(Builder builder) {
      super(builder);
    }
    private LoginRequest(boolean noInit) {}
    
    private static final LoginRequest defaultInstance;
    public static LoginRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.module.player.proto.PlayerModule.internal_static_LoginRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.module.player.proto.PlayerModule.internal_static_LoginRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string playerName = 1;
    public static final int PLAYERNAME_FIELD_NUMBER = 1;
    private java.lang.Object playerName_;
    public boolean hasPlayerName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          playerName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string passward = 2;
    public static final int PASSWARD_FIELD_NUMBER = 2;
    private java.lang.Object passward_;
    public boolean hasPassward() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPassward() {
      java.lang.Object ref = passward_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          passward_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswardBytes() {
      java.lang.Object ref = passward_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        passward_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      playerName_ = "";
      passward_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPlayerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassward()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswardBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswardBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.module.player.proto.PlayerModule.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.player.proto.PlayerModule.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.player.proto.PlayerModule.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.module.player.proto.PlayerModule.LoginRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.module.player.proto.PlayerModule.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.module.player.proto.PlayerModule.internal_static_LoginRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.module.player.proto.PlayerModule.internal_static_LoginRequest_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.module.player.proto.PlayerModule.LoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        playerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        passward_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.module.player.proto.PlayerModule.LoginRequest.getDescriptor();
      }
      
      public com.cn.common.module.player.proto.PlayerModule.LoginRequest getDefaultInstanceForType() {
        return com.cn.common.module.player.proto.PlayerModule.LoginRequest.getDefaultInstance();
      }
      
      public com.cn.common.module.player.proto.PlayerModule.LoginRequest build() {
        com.cn.common.module.player.proto.PlayerModule.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.module.player.proto.PlayerModule.LoginRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.module.player.proto.PlayerModule.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.module.player.proto.PlayerModule.LoginRequest buildPartial() {
        com.cn.common.module.player.proto.PlayerModule.LoginRequest result = new com.cn.common.module.player.proto.PlayerModule.LoginRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerName_ = playerName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.passward_ = passward_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.module.player.proto.PlayerModule.LoginRequest) {
          return mergeFrom((com.cn.common.module.player.proto.PlayerModule.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.module.player.proto.PlayerModule.LoginRequest other) {
        if (other == com.cn.common.module.player.proto.PlayerModule.LoginRequest.getDefaultInstance()) return this;
        if (other.hasPlayerName()) {
          setPlayerName(other.getPlayerName());
        }
        if (other.hasPassward()) {
          setPassward(other.getPassward());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPlayerName()) {
          
          return false;
        }
        if (!hasPassward()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              playerName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              passward_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string playerName = 1;
      private java.lang.Object playerName_ = "";
      public boolean hasPlayerName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPlayerName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        playerName_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      void setPlayerName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        playerName_ = value;
        onChanged();
      }
      
      // required string passward = 2;
      private java.lang.Object passward_ = "";
      public boolean hasPassward() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPassward() {
        java.lang.Object ref = passward_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          passward_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassward(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passward_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassward() {
        bitField0_ = (bitField0_ & ~0x00000002);
        passward_ = getDefaultInstance().getPassward();
        onChanged();
        return this;
      }
      void setPassward(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        passward_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:LoginRequest)
    }
    
    static {
      defaultInstance = new LoginRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:LoginRequest)
  }
  
  public interface RegisterRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string playerName = 1;
    boolean hasPlayerName();
    String getPlayerName();
    
    // required string passward = 2;
    boolean hasPassward();
    String getPassward();
  }
  public static final class RegisterRequest extends
      com.google.protobuf.GeneratedMessage
      implements RegisterRequestOrBuilder {
    // Use RegisterRequest.newBuilder() to construct.
    private RegisterRequest(Builder builder) {
      super(builder);
    }
    private RegisterRequest(boolean noInit) {}
    
    private static final RegisterRequest defaultInstance;
    public static RegisterRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegisterRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.module.player.proto.PlayerModule.internal_static_RegisterRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.module.player.proto.PlayerModule.internal_static_RegisterRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string playerName = 1;
    public static final int PLAYERNAME_FIELD_NUMBER = 1;
    private java.lang.Object playerName_;
    public boolean hasPlayerName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          playerName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string passward = 2;
    public static final int PASSWARD_FIELD_NUMBER = 2;
    private java.lang.Object passward_;
    public boolean hasPassward() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPassward() {
      java.lang.Object ref = passward_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          passward_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswardBytes() {
      java.lang.Object ref = passward_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        passward_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      playerName_ = "";
      passward_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPlayerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassward()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswardBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswardBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.module.player.proto.PlayerModule.RegisterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.RegisterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.RegisterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.RegisterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.RegisterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.RegisterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.RegisterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.player.proto.PlayerModule.RegisterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.player.proto.PlayerModule.RegisterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.RegisterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.module.player.proto.PlayerModule.RegisterRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.module.player.proto.PlayerModule.RegisterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.module.player.proto.PlayerModule.internal_static_RegisterRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.module.player.proto.PlayerModule.internal_static_RegisterRequest_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.module.player.proto.PlayerModule.RegisterRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        playerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        passward_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.module.player.proto.PlayerModule.RegisterRequest.getDescriptor();
      }
      
      public com.cn.common.module.player.proto.PlayerModule.RegisterRequest getDefaultInstanceForType() {
        return com.cn.common.module.player.proto.PlayerModule.RegisterRequest.getDefaultInstance();
      }
      
      public com.cn.common.module.player.proto.PlayerModule.RegisterRequest build() {
        com.cn.common.module.player.proto.PlayerModule.RegisterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.module.player.proto.PlayerModule.RegisterRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.module.player.proto.PlayerModule.RegisterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.module.player.proto.PlayerModule.RegisterRequest buildPartial() {
        com.cn.common.module.player.proto.PlayerModule.RegisterRequest result = new com.cn.common.module.player.proto.PlayerModule.RegisterRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerName_ = playerName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.passward_ = passward_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.module.player.proto.PlayerModule.RegisterRequest) {
          return mergeFrom((com.cn.common.module.player.proto.PlayerModule.RegisterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.module.player.proto.PlayerModule.RegisterRequest other) {
        if (other == com.cn.common.module.player.proto.PlayerModule.RegisterRequest.getDefaultInstance()) return this;
        if (other.hasPlayerName()) {
          setPlayerName(other.getPlayerName());
        }
        if (other.hasPassward()) {
          setPassward(other.getPassward());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPlayerName()) {
          
          return false;
        }
        if (!hasPassward()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              playerName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              passward_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string playerName = 1;
      private java.lang.Object playerName_ = "";
      public boolean hasPlayerName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPlayerName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        playerName_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      void setPlayerName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        playerName_ = value;
        onChanged();
      }
      
      // required string passward = 2;
      private java.lang.Object passward_ = "";
      public boolean hasPassward() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPassward() {
        java.lang.Object ref = passward_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          passward_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassward(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passward_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassward() {
        bitField0_ = (bitField0_ & ~0x00000002);
        passward_ = getDefaultInstance().getPassward();
        onChanged();
        return this;
      }
      void setPassward(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        passward_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:RegisterRequest)
    }
    
    static {
      defaultInstance = new RegisterRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:RegisterRequest)
  }
  
  public interface PlayerResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 playerId = 1;
    boolean hasPlayerId();
    long getPlayerId();
    
    // required string playerName = 2;
    boolean hasPlayerName();
    String getPlayerName();
    
    // required int32 level = 3;
    boolean hasLevel();
    int getLevel();
    
    // required int32 exp = 4;
    boolean hasExp();
    int getExp();
  }
  public static final class PlayerResponse extends
      com.google.protobuf.GeneratedMessage
      implements PlayerResponseOrBuilder {
    // Use PlayerResponse.newBuilder() to construct.
    private PlayerResponse(Builder builder) {
      super(builder);
    }
    private PlayerResponse(boolean noInit) {}
    
    private static final PlayerResponse defaultInstance;
    public static PlayerResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public PlayerResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cn.common.module.player.proto.PlayerModule.internal_static_PlayerResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cn.common.module.player.proto.PlayerModule.internal_static_PlayerResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getPlayerId() {
      return playerId_;
    }
    
    // required string playerName = 2;
    public static final int PLAYERNAME_FIELD_NUMBER = 2;
    private java.lang.Object playerName_;
    public boolean hasPlayerName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          playerName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 level = 3;
    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getLevel() {
      return level_;
    }
    
    // required int32 exp = 4;
    public static final int EXP_FIELD_NUMBER = 4;
    private int exp_;
    public boolean hasExp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getExp() {
      return exp_;
    }
    
    private void initFields() {
      playerId_ = 0L;
      playerName_ = "";
      level_ = 0;
      exp_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, exp_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPlayerNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, exp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cn.common.module.player.proto.PlayerModule.PlayerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.PlayerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.PlayerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.PlayerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.PlayerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.PlayerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.PlayerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.player.proto.PlayerModule.PlayerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cn.common.module.player.proto.PlayerModule.PlayerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cn.common.module.player.proto.PlayerModule.PlayerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cn.common.module.player.proto.PlayerModule.PlayerResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cn.common.module.player.proto.PlayerModule.PlayerResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cn.common.module.player.proto.PlayerModule.internal_static_PlayerResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cn.common.module.player.proto.PlayerModule.internal_static_PlayerResponse_fieldAccessorTable;
      }
      
      // Construct using com.cn.common.module.player.proto.PlayerModule.PlayerResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        playerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        playerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        exp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cn.common.module.player.proto.PlayerModule.PlayerResponse.getDescriptor();
      }
      
      public com.cn.common.module.player.proto.PlayerModule.PlayerResponse getDefaultInstanceForType() {
        return com.cn.common.module.player.proto.PlayerModule.PlayerResponse.getDefaultInstance();
      }
      
      public com.cn.common.module.player.proto.PlayerModule.PlayerResponse build() {
        com.cn.common.module.player.proto.PlayerModule.PlayerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cn.common.module.player.proto.PlayerModule.PlayerResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cn.common.module.player.proto.PlayerModule.PlayerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cn.common.module.player.proto.PlayerModule.PlayerResponse buildPartial() {
        com.cn.common.module.player.proto.PlayerModule.PlayerResponse result = new com.cn.common.module.player.proto.PlayerModule.PlayerResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.playerName_ = playerName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.exp_ = exp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cn.common.module.player.proto.PlayerModule.PlayerResponse) {
          return mergeFrom((com.cn.common.module.player.proto.PlayerModule.PlayerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cn.common.module.player.proto.PlayerModule.PlayerResponse other) {
        if (other == com.cn.common.module.player.proto.PlayerModule.PlayerResponse.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasPlayerName()) {
          setPlayerName(other.getPlayerName());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasPlayerName()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasExp()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              playerName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              level_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              exp_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 playerId = 1;
      private long playerId_ ;
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getPlayerId() {
        return playerId_;
      }
      public Builder setPlayerId(long value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string playerName = 2;
      private java.lang.Object playerName_ = "";
      public boolean hasPlayerName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPlayerName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        playerName_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      void setPlayerName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        playerName_ = value;
        onChanged();
      }
      
      // required int32 level = 3;
      private int level_ ;
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getLevel() {
        return level_;
      }
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 exp = 4;
      private int exp_ ;
      public boolean hasExp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getExp() {
        return exp_;
      }
      public Builder setExp(int value) {
        bitField0_ |= 0x00000008;
        exp_ = value;
        onChanged();
        return this;
      }
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        exp_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PlayerResponse)
    }
    
    static {
      defaultInstance = new PlayerResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PlayerResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegisterRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034protofile/PlayerModule.proto\"4\n\014LoginR" +
      "equest\022\022\n\nplayerName\030\001 \002(\t\022\020\n\010passward\030\002" +
      " \002(\t\"7\n\017RegisterRequest\022\022\n\nplayerName\030\001 " +
      "\002(\t\022\020\n\010passward\030\002 \002(\t\"R\n\016PlayerResponse\022" +
      "\020\n\010playerId\030\001 \002(\003\022\022\n\nplayerName\030\002 \002(\t\022\r\n" +
      "\005level\030\003 \002(\005\022\013\n\003exp\030\004 \002(\005B1\n!com.cn.comm" +
      "on.module.player.protoB\014PlayerModule"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_LoginRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_LoginRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LoginRequest_descriptor,
              new java.lang.String[] { "PlayerName", "Passward", },
              com.cn.common.module.player.proto.PlayerModule.LoginRequest.class,
              com.cn.common.module.player.proto.PlayerModule.LoginRequest.Builder.class);
          internal_static_RegisterRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RegisterRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RegisterRequest_descriptor,
              new java.lang.String[] { "PlayerName", "Passward", },
              com.cn.common.module.player.proto.PlayerModule.RegisterRequest.class,
              com.cn.common.module.player.proto.PlayerModule.RegisterRequest.Builder.class);
          internal_static_PlayerResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_PlayerResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PlayerResponse_descriptor,
              new java.lang.String[] { "PlayerId", "PlayerName", "Level", "Exp", },
              com.cn.common.module.player.proto.PlayerModule.PlayerResponse.class,
              com.cn.common.module.player.proto.PlayerModule.PlayerResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
